name: AI Code Review

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: AI PR Reviewer with Mistral
        uses: Onigam/ai-mistral-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        with:
          debug: false
          openai_base_url: "https://api.mistral.ai/v1"
          openai_light_model: "mistral-medium-latest"
          openai_heavy_model: "codestral-latest"
          review_simple_changes: false
          review_comment_lgtm: false
